# Generated by Django 3.1.4 on 2020-12-25 09:51

from django.db import migrations, models
import django.db.models.deletion
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('youtube', 'Youtube')], max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=posts.utils.post_files_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='posts.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
