# Generated by Django 3.1.4 on 2020-12-21 17:31

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201221_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='/static/img/user-cover-placeholder.jpg', upload_to=users.utils.build_user_cover_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/static/img/user-image-placeholder.jpg', upload_to=users.utils.build_user_image_path),
        ),
    ]
