# Generated by Django 3.1.4 on 2020-12-21 17:35

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201221_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(upload_to=users.utils.build_user_cover_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=users.utils.build_user_image_path),
        ),
    ]
