# Generated by Django 3.1.4 on 2020-12-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20201211_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussions.discussion'),
            preserve_default=False,
        ),
    ]
